project:
  type: book

book:
  title: "Australian ecosystems synthesis pipeline"
  subtitle: "Ecosystem Indicator Workflow"
  author: 
    - JR Ferrer-Paris
    - M Tozer
    - DA Keith
  chapters:
    - index.qmd
    - part: "Catalogue"
      chapters: 
      - file: "catalogue/index.qmd"
        text: "Summary"
      - file: "catalogue/AUS-NVIS-v7-State-files.ipynb"
        text: "NVIS 7.0"
      - file: "catalogue/QLD-REDD.ipynb"
        text: "Queensland RE"
      - file: "catalogue/TAS-TASVEG.ipynb"
        text: "Tasmania TASVEG"
      - file: "catalogue/ECNes.ipynb"
        text: "National TEC"
    - part: "GET Crossreferencing"
      chapters: 
      - file: "xref-matrix/index.qmd"
        text: "Summary"
#      - file: "xref-matrix/AUS-NEAP-IUCN-layers.ipynb"
#        text: "NEAP"
#      - file: "xref-matrix/MTozer-matrix.ipynb"
#        text: "National inventory"
    - part: "Examples"
      chapters: 
      - examples/index.qmd
#      - file: "examples/QLD-T1_1.ipynb"
#        text: "T1.1 in Queensland"
#      - file: "examples/QLD-REDD.ipynb"
#        text: "EFG in the Gayini wetlands"
    - file: Instructions.qmd
      text: "Instructions"
    - file: FAIR.qmd
      text: "FAIR notes"
    - references.qmd
  margin-header: |
    <center>
    ![](/assets/logo_CES.png){height=66px}
    </center>
  page-footer:
    left: "This site prepared by: [EIW project team](https://github.com/Ecosystem-Indicators-Workflows)"
    center: "![](/assets/unsw_new_logo.png){height=20px} We acknowledge the Bedegal and Gadigal peoples who are the Traditional Owners of the lands where UNSW Sydney is located. We pay our respects to Elders past and present."

bibliography: references.bib

format:
  html:
    theme: minty
    css: styles.css
    highlight-style: solarized
    toc: true
    sidebar-width: 300px # Default is 250px
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png